### ISSUE TITLE
Altering clock speed doesn't work

### ISSUE THREAD

**Issue by idiopathy** [ayurmedia/xnu-speedstep-air#1]
I think the compiled intelenhancedspeedstep.kext works great.  I am able to adjust allotted clock speed through kern.cputhrottle_curfreq=  and adjust target load.  I have complied it on my macbook pro 5.1 with the same intention of under clocking and undervolting to cool down my laptop.  However, I'd like to underclock it even more during idle.  But the compiled kext would only allow me 3 clock speed for the pstatetable 1995 mhz, 1862 mhz, 1592 mhz, and when I alter the value to other clock speed with similar multipliers of 133 like 1330 &1064 mhz .  It wouldn't go to those speed.

Would you know of where to edit the info.plist to allow slower clock speed for the speedstep?

**Comment by ayurmedia** [comment]
Hi, i think lower than 1592mhz is not possible with this xnu-speedstep, as it does not use the halfing of the frontsidebus or other tricks. there is no direct 1064mhz as i know, its more like 1995mhz with half fsb. 
on Lion in coolbook you could also not go below 1592mhz, on the white macbook 2,1 i could undervolt even more, i think on macbook 5,1 this is limited. 

if you have istat menus you can see that the native speedstep driver from apple goes down to 0,88v as xnu-speedstep is stuck at minimum 0.925 . it should be possible to undervolt to 0.9 or even lower but apple does not allow the kext to do it. 

also check if there is some if-statements for " mhz < 1000 " in the code which could prevent lower frequencies.

**Comment by ayurmedia** [comment]
maybe this piece of code gives some clue: 
in speedstep.cpp

if (Nby2Ratio && x < 1000) // FIXME: use n/2 for only <1ghz frequencies?
        realfid = (realfid*2) | 0x80;
    return realfid;

there is some trickery with n/2 which can enable frequencies below 1592, 
i had introduced some if for (71) but its not needed. 

i try to upload a newer version to github.

**Comment by ayurmedia** [comment]
i just uploaded my latest version. see the new folder "Tools" probably you need to adjust some paths in the *.command helperscripts.

**Comment by ayurmedia** [comment]
![screen shot 2014-06-10 at 20 58 53](https://cloud.githubusercontent.com/assets/1746990/3235287/7973ee72-f0d1-11e3-9851-e203d43af9f1.png)

![screen shot 2014-06-10 at 21 06 10](https://cloud.githubusercontent.com/assets/1746990/3235388/58bdcdf0-f0d2-11e3-96b3-d47a7cb31945.png)

running without removing AppleIntelCPU*.kexts the frequencies are overwritten by apple.kext all the time, but you can use it for debugging and watch settings. 
with xnu-kext and removed appleIntelCPU.kext i get to minimum of 0,92v also CPU-Ampere stays high. 
using original kext from 10.9 it goes below don't to 0.86 and 0.34A . 
i also try to set voltage to 900 (0.900) but its ignored and uses minimum of 0.925 (similar like coolbook). 

maybe somebody knows more about pstates and the P7350 chip to go lower.

**Comment by ayurmedia** [comment]
closed due to inactivity
